import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { Layout } from "ui";
import { trpc } from "utils/trpc";

const ComicPage: NextPage = () => {
  const router = useRouter();
  const comic = trpc.comic.getOneWithChapters.useQuery(
    { slug: router.query?.slug as string },
    { enabled: Boolean(router.query?.slug) }
  );

  return (
    <Layout>
      <Head>
        <title>4dcomics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout.Header className="flex items-center justify-between">
        <h1 className="text-2xl font-black">4dcomics</h1>
        <div />
      </Layout.Header>
      <div className="flex w-full bg-rose-300 py-8">
        <div className="mx-auto w-full max-w-[80em] px-4">
          <h2 className="text-5xl font-black">{comic.data?.title}</h2>
        </div>
      </div>
      <Layout.Main>
        <div className="mt-16 ">
          <img
            className=" h-[30em] w-full rounded-2xl object-cover"
            src={comic.data?.coverImage}
            alt="Cover image"
          />
        </div>
        <div className="my-16 flex flex-1 flex-col gap-4">
          {comic.data?.chapter?.map((chapter) => (
            <Link
              key={chapter.id}
              href={`/comics/${comic.data?.slug}/${chapter.ordinal}`}
            >
              <div className="flex w-full items-center justify-between bg-white p-8 ring-1 ring-stone-200 hover:bg-stone-100">
                <div className="flex items-center gap-8">
                  <img
                    className="h-20 w-20"
                    src={chapter.coverImage}
                    alt="Chapter image"
                  />
                  <p className="text-4xl font-bold">
                    Episode {chapter.ordinal}
                  </p>
                </div>
                <p className="text-2xl font-bold">
                  {chapter.createdAt.toLocaleDateString()}
                </p>
              </div>
            </Link>
          ))}
        </div>
      </Layout.Main>
    </Layout>
  );
};

export default ComicPage;
